baseURL = "https://ljpatrick.link/"
languageCode = "en-us"
title = "ljpatrick"
theme = "starter"

# prevent hugo from creating folders/indexes for each section
disableKinds = ["section"]

[permalinks]
    # :title is used if :slug is not defined in post frontmatter
    posts = "/posts/:year/:month/:slug/"
    archm = "/posts/:year/:month/"
    archy = "/posts/:year/"
